"""SI Fig d — are CLIMB embeddings redundant to classical features?

ONE script, ONE TABLE: figures_v2/SI_Fig_d.csv + SI_Fig_d.tex

The test is concatenation. If the CLIMB embedding carries signal the classical features do not,
then gluing it onto ECFP4+descriptors must beat ECFP4+descriptors alone. If it carries nothing
new, the concatenation is at best flat — and, because the extra 768 dimensions cost the model
degrees of freedom, may be slightly worse.

Four feature sets, same XGBoost head, same splits, same seeds:

  fp+desc       ECFP4 (2048 bits) + 217 RDKit descriptors   — the classical anchor
  CLM           the frozen CLIMB embedding alone
  desc+CLM      descriptors + CLIMB   (drops the fingerprint)
  fp+desc+CLM   everything            — the concatenation test

THE RESULT: concatenation helps on 1 of 6 tasks. On five — ESOL, QM7, BACE, Tox21, HIV —
`fp+desc+CLM` is WORSE than `fp+desc` alone, clearly so on the two regressions (ESOL 0.757 vs
0.730 RMSE; QM7 190.5 vs 187.5). The single exception is BBBP (+0.048 ROC-AUC, beyond its SD) —
and BBBP is precisely the dataset dropped from the paper's panel set for failing to discriminate:
its whole field spans 1.8% of ROC-AUC and an UNTRAINED random encoder ranks 7 of 16 on it
(notes/bbbp-anchor-verification-2026-08-16.md). A gain there is a gain on the one benchmark we
already decided cannot separate models, so it does not rescue the conclusion.

So on every benchmark that discriminates, the CLIMB embedding is redundant to the classical
featurization — it carries no information ECFP4+descriptors does not already carry — and CLIMB
alone is the weakest of the four feature sets on five of six tasks.

This is a negative result and it is reported as one. It is also the honest frame for Fig A1, where
ECFP+desc ranks first overall: the transformer is not adding a missing view of the molecule.

Emitted per (task, metric) with the primary metric first; `delta_vs_fp_desc` is signed so that
POSITIVE always means the concatenation helped, and `beats_sd` says whether that delta exceeds the
SD of the concatenated arm — the minimum bar for reading anything into it.

Source: analysis/rigor/concat_redundancy.csv (git-tracked).

Run:  python3 -m figures.fig_SI_d
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "analysis" / "rigor" / "concat_redundancy.csv"
OUTDIR = ROOT / "figures_v2"

TASKS = ["ESOL", "QM7", "BACE", "BBBP", "Tox21", "HIV"]
PRIMARY = {"ESOL": "rmse", "QM7": "rmse", "BACE": "roc_auc", "BBBP": "roc_auc",
           "Tox21": "roc_auc", "HIV": "roc_auc"}
LOWER_BETTER = {"rmse"}
FEATURES = ["fp+desc", "CLM", "desc+CLM", "fp+desc+CLM"]
BASE = "fp+desc"
CONCAT = "fp+desc+CLM"


def main():
    d = pd.read_csv(SRC)
    rows = []
    for task in TASKS:
        metric = PRIMARY[task]
        g = d[(d.task == task) & (d.metric == metric)].set_index("features")
        if BASE not in g.index or CONCAT not in g.index:
            continue
        sign = -1 if metric in LOWER_BETTER else 1
        base_v = float(g.loc[BASE, "mean"])
        row = dict(task=task, metric=metric)
        for f in FEATURES:
            row[f] = round(float(g.loc[f, "mean"]), 4) if f in g.index else ""
            row[f + "_sd"] = round(float(g.loc[f, "std"]), 4) if f in g.index else ""
        delta = sign * (float(g.loc[CONCAT, "mean"]) - base_v)
        sd = float(g.loc[CONCAT, "std"])
        row["delta_vs_fp_desc"] = round(delta, 4)
        row["concat_sd"] = round(sd, 4)
        row["beats_sd"] = "yes" if delta > sd else "no"
        rows.append(row)

    OUTDIR.mkdir(exist_ok=True)
    cols = ["task", "metric"] + [c for f in FEATURES for c in (f, f + "_sd")] + \
           ["delta_vs_fp_desc", "concat_sd", "beats_sd"]
    with open(OUTDIR / "SI_Fig_d.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)

    with open(OUTDIR / "SI_Fig_d.tex", "w") as fh:
        fh.write("% SI Fig d — CLIMB/classical redundancy. Generated by figures/fig_SI_d.py; do not hand-edit.\n")
        fh.write("\\begin{tabular}{llrrrrrl}\n\\hline\n")
        fh.write("Task & Metric & " + " & ".join(FEATURES) +
                 r" & $\Delta$ concat & $>$ SD? \\" + "\n\\hline\n")
        for r in rows:
            cells = " & ".join(f"{r[f]:.4g} $\\pm$ {r[f+'_sd']:.2g}" for f in FEATURES)
            fh.write(f"{r['task']} & {r['metric']} & {cells} & "
                     f"{r['delta_vs_fp_desc']:+.4g} & {r['beats_sd']} \\\\\n")
        fh.write("\\hline\n\\end{tabular}\n")

    print("\nSI Fig d — does concatenating CLIMB onto the classical features help?")
    print("  (delta signed so + = concatenation helped; primary metric per task)\n")
    print(f"  {'task':<7}{'metric':<9}" + "".join(f"{f:>22}" for f in FEATURES) +
          f"{'delta':>10}{'> SD?':>7}")
    for r in rows:
        line = f"  {r['task']:<7}{r['metric']:<9}"
        for f in FEATURES:
            line += f"{r[f]:>13.4f} ±{r[f+'_sd']:<8.4f}"
        line += f"{r['delta_vs_fp_desc']:>+10.4f}{r['beats_sd']:>7}"
        print(line)
    helped = sum(r["beats_sd"] == "yes" for r in rows)
    print(f"\n  concatenation beat its own SD on {helped}/{len(rows)} tasks")
    print("  wrote figures_v2/SI_Fig_d.csv + SI_Fig_d.tex")


if __name__ == "__main__":
    main()
