"""Insert (or refresh) the model-inventory section in README.md from audit/model_inventory.csv.

Regenerated rather than hand-maintained: a hand-typed table of 150+ runs goes stale the moment a
wave finishes, and a stale inventory is worse than none -- it is exactly the kind of artifact that
gets trusted and then turns out to be wrong.
"""
import csv, re
from collections import defaultdict
from pathlib import Path

# NOTE: `climb_v2_labeleff_v2` (the absolute-budget label-efficiency data) is DELIBERATELY excluded.
# Fig B1p1 was re-run at per-task FRACTIONS (5/10/25/50/100%); its data now lives in
# `analysis/rigor/label_efficiency_fractions_*.csv` (frozen arms) + `figure_data/climb_v2_labeleff_v2_frac_e2e`
# (e2e), not as absolute-budget per-run dirs. The label-efficiency inventory rows in README §9.6 are
# therefore HAND-MAINTAINED (see the E12 row and §9.1). Re-adding the old wave here would re-inject
# the superseded capped rows. If you re-audit label-efficiency, point this at the new sources first.
PAPER = ["climb_v2_phase2", "climb_v2_ablation_dedup", "climb_v2_h1"]
BEGIN = "<!-- BEGIN MODEL INVENTORY (generated by scripts/reproducibility_audit.py) -->"
END = "<!-- END MODEL INVENTORY -->"

rows = [r for r in csv.DictReader(open("audit/model_inventory.csv")) if r["wave"] in PAPER]
agg = defaultdict(lambda: dict(n=0, ck=0, cur=0, pf=0, sg=0, cv=0, pr=0, b=set(), s=set(), w=set()))
for r in rows:
    a = agg[r["pretraining"]]
    a["n"] += 1
    a["ck"] += 1 if float(r["encoder_s3_gb"] or 0) else 0
    a["cur"] += int(r["metrics_jsonl"]); a["pf"] += int(r["verified"])
    a["sg"] += int(r["eval::single-split summary"]); a["cv"] += int(r["eval::5-fold CV summary"])
    a["pr"] += int(r["eval::per-molecule CV predictions (I1)"])
    if r["budget"] != "-":
        a["b"].add(r["budget"])
    a["s"].add(r["seed"]); a["w"].add(r["wave"])

def order(b):
    m = re.match(r"(\d+)M", b)
    return (0, int(m.group(1))) if m else (1, b)

ck_gb = sum(float(r["encoder_s3_gb"] or 0) for r in rows)
n_ck = sum(1 for r in rows if float(r["encoder_s3_gb"] or 0))

L = [BEGIN, "",
     "### 9.6 Model inventory (what exists, and what we hold for it)",
     "",
     f"**{len(rows)} runs** across the four waves the paper draws on. Regenerate with",
     "`python scripts/reproducibility_audit.py --listing <s3 listing> --out audit/`; the per-run",
     "breakdown is `paper_artifacts/INVENTORY.md`.",
     "",
     "| Pretraining type | Budgets | Seeds | Runs | ckpt | curve | proof | single-split | 5-fold CV | CV preds |",
     "|---|---|---|--:|--:|--:|--:|--:|--:|--:|"]
for k in sorted(agg, key=lambda x: (x.startswith("label-efficiency"), x.startswith("classical"), x)):
    a = agg[k]
    b = ", ".join(sorted(a["b"], key=order)) or "—"
    na = lambda v, cond: (str(v) if cond else "n/a")
    trained = not (k.startswith("classical") or k.startswith("label-efficiency")
                   or k.startswith("no_pretrain"))
    L.append(f'| `{k}` | {b} | {",".join(sorted(a["s"]))} | {a["n"]} | '
             f'{na(a["ck"], not k.startswith(("classical","label-efficiency")))} | '
             f'{na(a["cur"], trained)} | {na(a["pf"], trained)} | '
             f'{a["sg"]} | {a["cv"]} | {a["pr"]} |')
L += ["",
      f"**{n_ck} encoder checkpoints, {ck_gb:.1f} GB**, indexed in `paper_artifacts/checkpoints.csv`",
      "with `fetch_checkpoint.sh <run>` to pull one. They are not mirrored to laptops.",
      "",
      "**Columns.** `ckpt` = encoder weights in S3 · `curve` = `metrics.jsonl` training curve ·",
      "`proof` = `verified.json`, written only once achieved forward passes reach ≥98% of budget ·",
      "`single-split` = DeepChem scaffold hold-out evaluation · `5-fold CV` = scaffold CV ·",
      "`CV preds` = per-molecule predictions (needed by Fig I1). `n/a` marks a column that cannot",
      "apply: classical anchors have no encoder, label-efficiency probes are *evaluations* of an",
      "existing 8M encoder at different label budgets rather than models of their own, and a",
      "random-init baseline has a checkpoint but no training curve and no forward-pass budget.",
      "",
      "**Evaluation.** Every model is scored on the same 7 tasks (ESOL, Lipophilicity, QM7, BBBP,",
      "BACE, Tox21, HIV) with 3 head seeds, under two schemes: the DeepChem scaffold hold-out",
      "(headline; rarest scaffolds in test) and 5-fold scaffold CV (split-variance error bars, and",
      "the only source of per-molecule predictions). Both emit train and test metrics; HIV also",
      "carries NEF1% (top-1% enrichment).",
      "",
      "**Storage.** Working bucket `s3://climb-s3-bucket`; independent versioned backup at",
      "`s3://climb-paper-backup-<acct>` (no expiry lifecycle, copy-only). The old",
      "`experiments/robust_matrix` wave (3.7 TB, 98.9% of it per-epoch fine-tuning checkpoints, read",
      "by no figure) is lifecycled to Glacier Deep Archive: ~$86/month → ~$4/month, data retained.",
      "", END]

readme = Path("README.md").read_text()
block = "\n".join(L)
if BEGIN in readme:
    readme = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, readme, flags=re.S)
else:
    readme = readme.replace("## 10. Limitations and known issues",
                            block + "\n\n---\n\n## 10. Limitations and known issues", 1)
Path("README.md").write_text(readme)
print(f"README.md: model inventory section written ({len(rows)} runs, {len(agg)} types)")
